### ISSUE TITLE
Cloudflare R2 Support

### ISSUE THREAD

**Issue by surjithctly** [hdoro/sanity-plugin-external-files#12]
Would be great if it could support cloudflare R2. It seems to be much cheaper than S3 and no egress fee.

**Comment by melvas6** [comment]
Hi
I'm new to Cloud storage
Can we use S3-compatible API of R2 to make this plugin work?
If yes, how to go about?
And what could be potential problems?

**Comment by emilianscheel** [comment]
I created a pull request which adds support for Cloudflare R2 Object Storage 
#17

**Comment by hdoro** [comment]
We're still in the process of finalizing the release cycle, but with @emilianscheel 's work `sanity-plugin-cloudflare-r2-files` will soon be available for download ✅
