### ISSUE TITLE
Sanity Studio v3 Support

### ISSUE THREAD

**Issue by surjithctly** [hdoro/sanity-plugin-external-files#13]
- [ ] Make this plugin compatible with Sanity Studio v3

**Comment by beninada** [comment]
@hdoro are there any plans to build support for Sanity Studio v3?

**Comment by mxmzb** [comment]
Just wanted to install it, so it's currently not compatible?

**Comment by surjithctly** [comment]
@hdoro You already did many amazing things for the Sanity Community. We are so grateful for your contributions. 

So this is completely understandable. Much love ❤️

**Comment by shaks786** [comment]
Trying to migrate this to v3 but finding it difficult to follow the Sanity docs - any guidance on where to start and what needs changing to migrate this to v3?

**Comment by felixhaeberle** [comment]
Is there any hope this will be ported to v3? would also contribute. with v2 nearing end of life at 7th December 2023, this holds the portability of our codebase back.

@hdoro are you willing to accept a PR?

@surjithctly @shaks786 @beninada @mxmzb let's do this together!

**Comment by paulhchoi** [comment]
thank you @hdoro for your continued work on this! I'm newer to this and was wondering how, exactly, I could install your "^1.0.0-next.1" version? for me, I'm looking to link Sanity V3 and S3, and neither `sanity add s3-dam@^1.0.0-next.1` nor `yarn add sanity-plugin-external-files@^1.0.0-next.1` seem to be available to use

**Comment by shaks786** [comment]
> thank you @hdoro for your continued work on this! I'm newer to this and was wondering how, exactly, I could install your "^1.0.0-next.1" version? for me, I'm looking to link Sanity V3 and S3, and neither `sanity add s3-dam@^1.0.0-next.1` nor `yarn add sanity-plugin-external-files@^1.0.0-next.1` seem to be available to use

Did you manage to figure it out?

**Comment by viswongdev** [comment]
> > thank you @hdoro for your continued work on this! I'm newer to this and was wondering how, exactly, I could install your "^1.0.0-next.1" version? for me, I'm looking to link Sanity V3 and S3, and neither `sanity add s3-dam@^1.0.0-next.1` nor `yarn add sanity-plugin-external-files@^1.0.0-next.1` seem to be available to use
> 
> Did you manage to figure it out?

Has anyone figured it out?
