### ISSUE TITLE
Allow users to upload additional file types

### ISSUE THREAD

**Issue by nkgentile** [hdoro/sanity-plugin-external-files#6]
## Description
Ideally, this plugin could be extended to allow for uploads of any file type: images, PDF's, etc. Additionally, the plugin could expose a few configuration options that are currently private (`defaultAccept`, `toolTitle`). This request was raised in the [Sanity Community Slack](https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1656606862306349).

**Comment by hdoro** [comment]
Done as per your work on #7 :)
